- hosts: localhost
  vars:
          - key: "adi_key_march"
          - type: t2.micro
          - image: ami-068d43a544160b7ef
          - region: ap-south-1
          - sg: sg-02a140eb95ffc2389
  tasks:
          - name: Creating new instance
            ec2_instance:
                    name: "Job-Tracker"
                    security_group: "{{ sg }}"
                    key_name: "{{ key }}"
                    instance_type: "{{ type }}"
                    image_id : "{{ image }}"
                    region: "{{ region }}"
                    wait: yes
                    vpc_subnet_id: "subnet-611c1509"
            register: master

          - name: Updating local Inventory
            lineinfile:
                  path: './inventory'
                  regexp: '^proxyservers'
                  line: '{{ master.instances[0].public_ip_address }}'
                  insertafter: '[proxyservers]' 

