- hosts: all
  vars:
          - port: "8080"
  tasks:
          - name: installing httpd
            yum:
                    name: httpd
                    state: present
          
          - name: Copying html file
            copy:
                    src: "./conf-file/index.html"
                    dest: "/var/www/html/"

          - name: Copying conf file
            template:
                    src: "./conf-file/httpd.conf"
                    dest: "/etc/httpd/conf/"
            notify:
                    - Restart_service_httpd

  handlers:
          - name: Restart_service_httpd
            service:
                    name: httpd
                    state: restarted
            register: output

          - name: Output if httpd restarted
            debug:
                    msg: "output.changed"
