- hosts: localhost
  vars_prompt:
          - name: c_name
            prompt: "Give your container a good name "
            private: no
  vars:
          - c_image: "aditya0707/ssh_image"
          - version: "v1"

  tasks:
          - name: Creating Docker Repository
            yum_repository:
                  name: "docker"
                  baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                  gpgcheck: no
                  description: "Docker-install"
            notify: install_docker

          - name: Starting Docker services
            service:
                    name: docker
                    state: restarted
                    enabled: yes

          - name: Creating Docker container
            docker_container:
                    name: "{{ c_name }}"
                    image: "{{ c_image }}:{{ version }}"
                    tty: yes
                    interactive: yes
                    published_ports:                      
                            - 0.0.0.0:1234:80/tcp
                    exposed_ports:
                            - 80/tcp
                    state: started

            register: output

          - name: IP of the launched container
            debug:
                    msg: "{{ output.ansible_facts['docker_container'].NetworkSettings['IPAddress'] }}"

          - name: Updating inventory
            blockinfile:
                    path: "./inventory"
                    block: |
                            [docker]
                            {{ output.container.NetworkSettings.IPAddress }}  ansible_ssh_user=root ansible_ssh_pass='redhat'
          - name: Cooking Webpage
            template:
                    src: "./index.php.j2"
                    dest: "./index.html"

          - pause:
                  seconds: 5

  handlers:
          - name: install_docker
            command: "yum install docker-ce --nobest -y"
            notify: restart

          - name: restart
            service:
                    name: docker
                    state: restarted
            notify: Installing Docker SDK

          - name: Installing Docker SDK
            pip:
                    name: docker-py
