- hosts: localhost
  vars:
          - key: "adi_key_march"
          - type: t2.micro
          - image: ami-068d43a544160b7ef
          - region: ap-south-1
          - sg: sg-02a140eb95ffc2389
  vars_prompt:
          name: "instance_name"
          prompt: "Give sever name "
          private: no
  tasks:
          - name: Creating new instance
            ec2_instance:
                    name: "{{ instance_name }}"
                    security_group: "{{ sg }}"
                    key_name: "{{ key }}"
                    instance_type: "{{ type }}"
                    image_id : "{{ image }}"
                    region: "{{ region }}"
                    wait: yes
                    vpc_subnet_id: "subnet-611c1509"
            register: os

          - name: IP of Launched Instance
            debug:
                    var:  os.instances[0].public_ip_address

          - name: Updating local Load Balancer Conf file
            lineinfile:
                  path: 'conf-file/haproxy.cfg'
                  regexp: '^server'
                  line: '     server  app{{ instance_name }} {{ os.instances[0].public_ip_address }}:80 check'
                  insertbefore: '#    server  app1 127.0.0.1:5001 check' 
          
          - name: Updating local Inventory
            lineinfile:
                  path: './inventory'
                  regexp: '^proxyservers'
                  line: '{{ os.instances[0].public_ip_address }}'
                  insertafter: '[proxyservers]' 
