- hosts: localhost
  roles:
          - ec2
            
  tasks:
          - name: Waiting for the instances to get ready
            pause:
                    minutes: 3

- hosts: all
  roles:
          - cluster
